Apply fix for upstream bug 7281
ImportError: cannot import name 'gpgme' from partially initialized module 'gpg' (most likely due to a circular import) (/usr/lib/python3.12/site-packages/gpg/__init__.py)